### ISSUE TITLE
Help! How to use it?

### ISSUE THREAD

**Issue by hakavlad** [ivanfitenko/oom_ext#1]
Hello! Could you tell me how to install and use it?

**Comment by ivanfitenko** [comment]
Readme will be available in less than 24h, thank you

**Comment by ivanfitenko** [comment]
Readme is added with PR #3, sorry for such a long delay (hm, looks like there's something wrong with my email notifications)

**Comment by hakavlad** [comment]
@ivanfitenko thank you!
